package gornparser_test

import (
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gornkit/gorn/pkg/gornparser"
)

func TestGenerateProducesModuleAndFormattedMain(t *testing.T) {
	source := []byte("//gorn:go 1.26\n" +
		"//gorn:module example.com/scripts/hello\n" +
		"//gorn:require github.com/example/tool v1.2.3\n" +
		"\n" +
		"import \"fmt\"\n" +
		"\n" +
		"//gorn:main\n" +
		"\n" +
		"fmt.Println(\"hello\")\n" +
		"sh.Host()\n")

	script, err := gornparser.ParseSource("hello.gorn", source)
	if err != nil {
		t.Fatal(err)
	}

	generated, err := gornparser.Generate(script)
	if err != nil {
		t.Fatal(err)
	}

	wantMod := "module example.com/scripts/hello\n\n" +
		"go 1.26\n" +
		"require (\n" +
		"\tgithub.com/example/tool v1.2.3\n" +
		")\n"
	if got := string(generated.ModGenerated); got != wantMod {
		t.Fatalf("ModGenerated = %q, want %q", got, wantMod)
	}

	mainFile := string(generated.MainFileFormatted)
	for _, want := range []string{
		"// Code generated by gorn from hello.gorn; DO NOT EDIT.",
		"package main",
		"import \"fmt\"",
		"func main() {",
		"\tfmt.Println(\"hello\")",
		"\tsh.Host()",
	} {
		if !strings.Contains(mainFile, want) {
			t.Fatalf("formatted main missing %q:\n%s", want, mainFile)
		}
	}
	if strings.Contains(mainFile, "gorn.dev/gorn/sh") {
		t.Fatalf("formatted main uses stale sh import path:\n%s", mainFile)
	}
}

func TestGenerateDefaultsModuleWhenOmitted(t *testing.T) {
	source := []byte("//gorn:go 1.26\n" +
		"//gorn:main\n" +
		"println(\"hello\")\n")

	script, err := gornparser.ParseSource("hash.gorn", source)
	if err != nil {
		t.Fatal(err)
	}

	generated, err := gornparser.Generate(script)
	if err != nil {
		t.Fatal(err)
	}

	want := "module gorn.local/app\n\n" +
		"go 1.26\n"
	if got := string(generated.ModGenerated); got != want {
		t.Fatalf("ModGenerated = %q, want %q", got, want)
	}
}

// TestGenerateDefaultsGoVersionWhenOmitted guards against emitting an
// invalid go.mod ("go \n" with no version) when a script has no //gorn:go
// directive. GoVersion is optional at parse time, so Generate must supply
// a usable default.
func TestGenerateDefaultsGoVersionWhenOmitted(t *testing.T) {
	source := []byte("//gorn:main\n" +
		"println(\"hello\")\n")

	script, err := gornparser.ParseSource("no-go-version.gorn", source)
	if err != nil {
		t.Fatal(err)
	}
	if script.GoVersion != "" {
		t.Fatalf("GoVersion = %q, want empty (test assumes //gorn:go is optional)", script.GoVersion)
	}

	generated, err := gornparser.Generate(script)
	if err != nil {
		t.Fatal(err)
	}

	mod := string(generated.ModGenerated)
	if strings.Contains(mod, "go \n") || strings.Contains(mod, "go\n") {
		t.Fatalf("ModGenerated has no go version:\n%s", mod)
	}
	if !strings.Contains(mod, "go 1.26\n") {
		t.Fatalf("ModGenerated missing expected default go version:\n%s", mod)
	}
}

func TestGenerateReturnsRawMainWhenFormattingFails(t *testing.T) {
	source := []byte("//gorn:go 1.26\n" +
		"//gorn:main\n" +
		"if {\n")

	script, err := gornparser.ParseSource("bad-go.gorn", source)
	if err != nil {
		t.Fatal(err)
	}

	generated, err := gornparser.Generate(script)
	if generated != nil {
		t.Fatalf("Generated = %+v, want nil on format failure", generated)
	}
	var genErr *gornparser.GenerateError
	if !errors.As(err, &genErr) {
		t.Fatalf("error type = %T, want *gornparser.GenerateError", err)
	}
	if len(genErr.Raw) == 0 {
		t.Fatal("GenerateError.Raw is empty, want raw generated source")
	}
}

func TestGenerateRejectsPreambleImportConflict(t *testing.T) {
	tests := []struct {
		name     string
		source   string
		wantLine int
	}{
		{
			name: "single import",
			source: "//gorn:preamble\n" + // 1
				"\n" + // 2
				"import \"strings\"\n" + // 3
				"//gorn:main\n" + // 4
				"strings.ToUpper(\"x\")\n", // 5
			wantLine: 3,
		},
		{
			name: "import block",
			source: "//gorn:preamble\n" + // 1
				"import (\n" + // 2
				"\t\"fmt\"\n" + // 3
				"\t\"strings\"\n" + // 4
				")\n" + // 5
				"//gorn:main\n" + // 6
				"fmt.Println()\n", // 7
			wantLine: 3,
		},
		{
			name: "aliased import still conflicts by path",
			source: "//gorn:preamble\n" + // 1
				"import f \"fmt\"\n" + // 2
				"//gorn:main\n" + // 3
				"f.Println()\n", // 4
			wantLine: 2,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			script, err := gornparser.ParseSource("conflict.gorn", []byte(tt.source))
			if err != nil {
				t.Fatal(err)
			}
			_, err = gornparser.Generate(script)
			if !errors.Is(err, gornparser.ErrPreambleImportConflict) {
				t.Fatalf("error = %v, want errors.Is(_, %v)", err, gornparser.ErrPreambleImportConflict)
			}
			var parseErr *gornparser.Error
			if !errors.As(err, &parseErr) {
				t.Fatalf("error type = %T, want *gornparser.Error", err)
			}
			if parseErr.Line != tt.wantLine {
				t.Fatalf("error line = %d, want %d", parseErr.Line, tt.wantLine)
			}
		})
	}
}

func TestGenerateAllowsNonPreambleImportsWithPreamble(t *testing.T) {
	source := []byte("//gorn:preamble\n" +
		"\n" +
		"import \"github.com/example/tool\"\n" +
		"//gorn:main\n" +
		"tool.Do()\n")

	script, err := gornparser.ParseSource("ok.gorn", source)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := gornparser.Generate(script); err != nil {
		t.Fatalf("Generate = %v, want nil", err)
	}
}

func TestGenerateSkipsConflictCheckWithoutPreamble(t *testing.T) {
	// Without //gorn:preamble, importing fmt is perfectly normal and must
	// not be flagged.
	source := []byte("import \"fmt\"\n" +
		"//gorn:main\n" +
		"fmt.Println()\n")

	script, err := gornparser.ParseSource("no-preamble.gorn", source)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := gornparser.Generate(script); err != nil {
		t.Fatalf("Generate = %v, want nil", err)
	}
}

// TestGeneratePreambleOutputCompiles is the real guard against generated
// output that gofmt accepts but the Go compiler rejects (e.g. an undefined
// keep-alive symbol, or an unused import). It builds a preamble script that
// references none of the preamble packages directly, in a temp module that
// replaces gorn with this working tree.
func TestGeneratePreambleOutputCompiles(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping go build in short mode")
	}

	source := []byte("//gorn:go 1.26\n" +
		"//gorn:preamble\n" +
		"//gorn:main\n" +
		"println(\"no preamble packages used directly\")\n")

	script, err := gornparser.ParseSource("compile.gorn", source)
	if err != nil {
		t.Fatal(err)
	}
	generated, err := gornparser.Generate(script)
	if err != nil {
		t.Fatal(err)
	}

	repoRoot, err := filepath.Abs("../..")
	if err != nil {
		t.Fatal(err)
	}

	dir := t.TempDir()
	goMod := string(generated.ModGenerated) +
		"\nrequire github.com/gornkit/gorn v0.0.0\n" +
		"replace github.com/gornkit/gorn => " + repoRoot + "\n"
	writeFile(t, filepath.Join(dir, "go.mod"), goMod)
	writeFile(t, filepath.Join(dir, "main.go"), string(generated.MainFileFormatted))

	runGo(t, dir, "mod", "tidy")
	runGo(t, dir, "build", "./...")
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}

func runGo(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("go", args...) //nolint:gosec // args are test-controlled literals
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go %s failed: %v\n%s", strings.Join(args, " "), err, out)
	}
}
